[workspace]
resolver = "2"

members = [
    "contracts/github",
    "contracts/flow",
    "contracts/stamp",
    "contracts/gig",
    "contracts/nexus",
    "contracts/soul",
    "contracts/zpay",
    "contracts/adapters/axelar",
    "contracts/adapters/authority-pull",
    "contracts/will",
    "contracts/mock_gateway",
    "verifiers/cosmos",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
