#!/bin/bash

# Build and deploy GitHub Identity contract to Stellar testnet

set -e

echo "🔨 Building contract (optimized)..."
# Use the CLI build with optimize flag to produce an optimized wasm in the workspace target
stellar contract build --optimize

# Path to the built wasm (relative to this script). The CLI builds under the workspace `target` dir.
WASM_PATH="$(pwd)/../../target/wasm32v1-none/release/github_identity.wasm"

if [ ! -f "$WASM_PATH" ]; then
  echo "❌ Unable to find wasm file at: $WASM_PATH"
  echo "   Looked for the file generated by 'stellar contract build'."
  exit 1
fi

echo "🚀 Deploying to testnet..."
CONTRACT_ID=$(stellar contract deploy \
  --wasm "$WASM_PATH" \
  --network testnet \
  --source deployer)

echo "✅ Contract deployed!"
echo "Contract ID: $CONTRACT_ID"
echo ""
echo "Save this to your .env:"
echo "STELLAR_GITHUB_IDENTITY_CONTRACT=$CONTRACT_ID"
echo ""
echo "Next steps:"
echo "1. Initialize contract with: ./scripts/initialize.sh $CONTRACT_ID"
echo "2. Update frontend with contract ID"
