[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
zolvency_verifier_solana = "FM344TprtFfP39Q4Td4ZXpamaCLfhDc4Qa61ygpGcou8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
